name: Deploy to Cloud Run

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: daf_epubs  # Define the project directory as an environment variable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: "auth"
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          
      - name: Configure Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: "Docker auth"
        run: |
          gcloud auth configure-docker ${{ secrets.GCR_REGION }}-docker.pkg.dev --quiet

      - name: Build Docker image
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          docker build -t ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ART_REG_REPO_NAME }} .

      - name: Push Docker image
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          docker push ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ART_REG_REPO_NAME }}

      - name: Deploy to Cloud Run
        working-directory: ${{ env.PROJECT_DIR }}
        run: |
          gcloud run deploy ${{ secrets.GCP_CLOUD_RUN_APP_NAME }} \
            --image ${{ secrets.GCR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ART_REG_REPO_NAME }} \
            --platform managed \
            --region us-central1 \
            --update-env-vars \
              ENVIRONMENT=production \
              SUPABASE_USER=${{ secrets.SUPABASE_USER }} \
              SUPABASE_PASSWORD=${{ secrets.SUPABASE_PASSWORD }} \
              SUPABASE_HOST=${{ secrets.SUPABASE_HOST }} \
              SUPABASE_PORT=${{ secrets.SUPABASE_PORT }} \
              SUPABASE_DB=${{ secrets.SUPABASE_DB }} \
              GCP_STORAGE_BUCKET_NAME=${{ secrets.GCP_STORAGE_BUCKET_NAME }} \
              GCP_STORAGE_ACCESS_KEY=${{ secrets.GCP_STORAGE_ACCESS_KEY }} \
              GCP_STORAGE_SECRET=${{ secrets.GCP_STORAGE_SECRET }} \
              GCP_STORAGE_URI=${{ secrets.GCP_STORAGE_URI }}
            --allow-unauthenticated
  